# deployments/helm/values-staging.yaml

replicaCount: 2

image:
  tag: "staging"

ingress:
  enabled: true
  hosts:
    - host: staging-api.events.pecdevelopers.com
      paths:
        - path: /
          pathType: ImplementationSpecific

env:
  springProfilesActive: "staging"
  databaseUrl: "jdbc:postgresql://postgres-staging-endpoint:5432/pec_events_staging"
